# How often to read the game memory
# You likely shouldn't change this
UpdateTime: 30

# Areas to preload so that they're hot and ready as soon as you go to them
PrefetchAreas:
 - 'Catacombs Level 2'
 - 'Durance Of Hate Level 2'

# Areas where the map should not show
# This includes all the towns and various crappy areas
# where you really don't need it.
HiddenAreas:
 - 'Rogue Encampment'
 - 'Lut Gholein'
 - 'Kurast Docktown'
 - 'The Pandemonium Fortress'
 - 'Harrogath'
 - 'Forgotten Tower'
 - 'Nihlathaks Temple'
ClearPrefetchedOnAreaChange: true
RenderingConfiguration:
  # Overlay mode defaults
  # Comment these out and uncomment block below to go to oldschool mode
  Opacity: 0.5
  OverlayMode: true
  # Possible positions: Center, TopLeft, TopRight
  Position: Center
  # If set to false it will always show unless you use the hotkeys to disable it
  ToggleViaInGameMap: false
 
  # Non-overlay mode defaults
  # Uncomment these out to go to oldschool mode
  # Opacity: 0.5
  # OverlayMode: false
  # Position: TopRight
  # If set to false it will always show unless you use the hotkeys to disable it
  # ToggleViaInGameMap: true
  
  AlwaysOnTop: true
  Size: 450
  Rotate: true
  ZoomLevel: 1
  BuffPosition: Bottom
  BuffSize: 1
MapConfiguration:
  SuperUniqueMonster:
    IconColor: Yellow
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  UniqueMonster:
    IconColor: DarkOrange
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  EliteMonster:
    IconColor: DarkRed
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  NormalMonster:
    IconColor: Gray
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  NextArea:
    IconColor: '237, 107, 0'
    IconShape: Square
    IconSize: 10
    LineColor: Chartreuse
    LineThickness: 2
    ArrowHeadSize: 10
    LabelColor: Chartreuse
    LabelFontSize: 8
    LabelFont: 'Helvetica'
  PreviousArea:
    IconColor: '255, 0, 149'
    IconShape: Square
    IconSize: 10
    LineColor: ''
    LabelColor: Chartreuse
    LabelFontSize: 8
    LabelFont: 'Helvetica'
  Waypoint:
    IconColor: '16, 140, 235'
    IconShape: Square
    IconSize: 10
  Quest:
    LineColor: Chartreuse
    LineThickness: 2
    ArrowHeadSize: 5
  Player:
    IconColor: '255, 255, 0'
    IconShape: Square
    IconSize: 5
    IconThickness: 2
  SuperChest:
    IconColor: '17, 255, 0'
    IconShape: Ellipse
    IconSize: 10
  NormalChest:
    IconColor: '96, 96, 96'
    IconShape: Square
    IconSize: 5
  Shrine:
    IconColor: '255, 218, 100'
    IconShape: Polygon
    IconSize: 10
  ArmorWeapRack:
    IconColor: '132, 132, 132'
    IconShape: Square
    IconSize: 4
  Item: 
    IconColor: 'DarkOrange'
    IconShape: Ellipse
    IconSize: 6
    LabelFont: 'Helvetica'
    LabelFontSize: 8
MapColorConfiguration:
  MapColors:
    '0': '50, 50, 50'
    '2': '10, 51, 23'
    '3': '255, 255, 255'
    '4': '0, 255, 255'
    '6': '50, 50, 50'
    '7': '0, 0, 0'
    '16': '50, 50, 50'
    '17': '50, 50, 50'
    '19': '100, 100, 100'
    '20': '40, 40, 40'
    '21': '50, 50, 50'
    '23': '120, 120, 120'
    '33': '0, 0, 0'
    '37': '0, 0, 0'
    '39': '0, 0, 0'
    '53': '0, 0, 0'
HotkeyConfiguration:
  ToggleKey: '\'
  ZoomInKey: '+'
  ZoomOutKey: '-'
  GameInfoKey: '['
ApiConfiguration:
  Endpoint: 'http://localhost:8080/'
  Token: ''
GameInfo:
  Enabled: true
  # Developer setting, probably not useful
  ShowOverlayFPS: false
# Set an IP you want to hunt
HuntingIP: 'x.x.x.x'
ItemLog:
  Enabled: true
  FilterFileName: "ItemFilter.yaml"
  PlaySoundOnDrop: true
  # Must be a .wav file, path relative to MapAssist location
  SoundFile: ""
  DisplayForSeconds: 45
  LabelFont: "Helvetica"
  LabelFontSize: 14