# IMPORTANT: After changing anything in this file, ensure validity using https://jsonformatter.org/yaml-validator

## HotkeyConfiguration - Keyboard shortcuts for the overlay
HotkeyConfiguration:
  ToggleKey: '|'
  ZoomInKey: 'Num +'
  ZoomOutKey: 'Num -'
  AreaLevelKey: '['

## HiddenAreas - Areas where the overlay is not needed and will be hidden
HiddenAreas:
  - 'Rogue Encampment'
  - 'Lut Gholein'
  - 'Kurast Docks'
  - 'Pandemonium Fortress'
  - 'Harrogath'
  - 'Forgotten Tower'
  - "Nihlathak's Temple"

## RenderingConfiguration - Visual settings for the overlay
RenderingConfiguration:
  ## Opacity - Map transparency %
  Opacity: 0.5
  ## Opacity - Icon transparency %
  IconOpacity: 0.9
  ## OverlayMode - Overlay map over in-game map / can be hidden with hotkey (ToggleKey)
  OverlayMode: true
  ## Positions - Options are: Center, TopLeft, TopRight
  Position: Center
  ## ToggleViaInGameMap - Auto-hide map overlay when the in-game map is hidden
  ToggleViaInGameMap: false
  ## ToggleViaInGamePanels - Auto-hide overlay when in-game panels/menus are opened
  ToggleViaInGamePanels: true
  ## Size - Overlay map maximum size
  Size: 800
  ## ZoomLevel - Zoom level / can zoom in/out with hotkeys (ZoomInKey, ZoomOutKey)
  ZoomLevel: 1
  ## BuffPosition - Options are: Player, Top, Bottom
  BuffPosition: Bottom
  ## BuffSize - Size of the buff icons (0.8 = 80%, 1 = 100%, 1.2 = 120%)
  BuffSize: 1

## MapConfiguration -- Visual settings for icons, lines and labels
MapConfiguration:
  SuperUniqueMonster:
    IconShape: Cross
    IconOutlineColor: Yellow
    IconSize: 6
    IconThickness: 2
  UniqueMonster:
    IconShape: Cross
    IconOutlineColor: DarkOrange
    IconSize: 6
    IconThickness: 2
  EliteMonster:
    IconShape: Cross
    IconOutlineColor: DarkRed
    IconSize: 6
    IconThickness: 2
  NormalMonster:
    IconShape: Cross
    IconOutlineColor: Gray
    IconSize: 6
    IconThickness: 2
  NextArea:
    IconShape: Square
    IconColor: SpringGreen
    IconSize: 5
    LineColor: SpringGreen
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: SpringGreen
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  PreviousArea:
    IconShape: Square
    IconColor: Violet
    IconSize: 5
    LineColor: ''
    LabelColor: Violet
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  Waypoint:
    IconShape: Square
    IconColor: SteelBlue
    IconSize: 5
  Quest:
    LineColor: Tomato
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Tomato
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  Player:
    IconShape: Cross
    IconOutlineColor: Chartreuse
    IconSize: 6
    IconThickness: 2
    LabelColor: Chartreuse
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  NonPartyPlayer:
    IconShape: Cross
    IconOutlineColor: Orange
    IconSize: 6
    IconThickness: 2
    LabelColor: Orange
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  HostilePlayer:
    IconColor: Red
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Red
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
    LineColor: Red
    LineThickness: 2
    ArrowHeadSize: 15
  Corpse:
    IconColor: Magenta
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Magenta
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
    LineColor: Magenta
    LineThickness: 2
    ArrowHeadSize: 15
  Portal:
    IconShape: Portal
    IconOutlineColor: Yellow
    IconSize: 3
    IconThickness: 2
    LabelColor: Yellow
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  SuperChest:
    IconShape: Square
    IconColor: '17, 255, 0'
    IconSize: 4
  NormalChest:
    IconColor: '17, 128, 0'
    IconShape: Square
    IconSize: 3
  LockedChest:
    IconColor: '128, 0, 0'
    IconSize: 3
  TrappedChest:
    IconColor: '255, 0, 0'
    IconShape: Square
    IconSize: 4
    IconThickness: 1
  Shrine:
    IconShape: Polygon
    IconColor: '255, 218, 100'
    IconSize: 5
    LabelColor: '255, 218, 100'
    LabelFontSize: 16
    LabelFont: 'Exocet Blizzard Mixed Caps'
  ArmorWeapRack:
    IconShape: Square
    IconColor: '132, 132, 132'
    IconSize: 4
  Item: 
    IconShape: Ellipse
    IconColor: DarkOrange
    IconSize: 4
    LabelFont: 'Exocet Blizzard Mixed Caps'
    LabelFontSize: 16

## ItemLog - Alerts for in-game dropped items nearby
ItemLog:
  Enabled: true
  FilterFileName: "ItemFilter.yaml"
  ## PlaySoundOnDrop - Play drop sound
  PlaySoundOnDrop: true
  ## SoundFile - Name of .wav file for drop sound (put .wav file in the MapAssist folder)
  SoundFile: ""
  DisplayForSeconds: 45
  LabelFont: "Exocet Blizzard Mixed Caps"
  LabelFontSize: 14

## MapColorConfiguration - Color schema for drawing overlay map
MapColorConfiguration:
  Walkable:
  Border: '255, 255, 255'

## GameInfo - Display setting for game info
GameInfo:
  ## ShowGameIP - Display game server IP address
  ShowGameIP: true
  ## HuntingIP - Set an IP address to display in green instead of red
  HuntingIP: 'x.x.x.x'
  ## ShowAreaLevel - Display current area and alvl
  ShowAreaLevel: true
  ## ShowOverlayFPS - Developer setting, probably not useful
  ShowOverlayFPS: false
  LabelFont: "Exocet Blizzard Mixed Caps"
  LabelFontSize: 14

## Path to D2LOD installation. Optional.
## Should only need to provide if we are not able to look it up
## automatically via the registry
D2Path: ''

Language: 0
