# Change these settings from the Config GUI provided in MapAssist
HotkeyConfiguration:
  ToggleKey: '|'
  AreaLevelKey: '['
  ZoomInKey: Num +
  ZoomOutKey: Num -
HiddenAreas:
- Rogue Encampment
- Lut Gholein
- Kurast Docktown
- Pandemonium Fortress
- Harrogath
- Forgotten Tower
- Nihlathaks Temple
RenderingConfiguration:
  Opacity: 0.5
  IconOpacity: 0.9
  OverlayMode: true
  Position: Center
  ToggleViaInGameMap: false
  ToggleViaInGamePanels: true
  StickToLastGameWindow: false
  Size: 800
  ZoomLevel: 1
  BuffPosition: Bottom
  BuffSize: 1
MapConfiguration:
  SuperUniqueMonster:
    IconOutlineColor: Yellow
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  UniqueMonster:
    IconOutlineColor: DarkOrange
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  ChampionMonster:
    IconOutlineColor: DarkRed
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  MinionMonster:
    IconOutlineColor: 255, 150, 150
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  NormalMonster:
    IconOutlineColor: Gray
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  Npc:
    IconOutlineColor: 196, 196, 196
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
    LabelColor: 199, 179, 119
    LabelFontSize: 14
    LabelFont: Formal 436
  NextArea:
    IconColor: SpringGreen
    IconShape: Square
    IconSize: 5
    LineColor: SpringGreen
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: SpringGreen
    LabelFontSize: 14
    LabelFont: Formal 436
  PreviousArea:
    IconColor: Violet
    IconShape: Square
    IconSize: 5
    LabelColor: Violet
    LabelFontSize: 14
    LabelFont: Formal 436
  Waypoint:
    IconColor: SteelBlue
    IconShape: Square
    IconSize: 5
  Quest:
    LineColor: Tomato
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Tomato
    LabelFontSize: 14
    LabelFont: Formal 436
  Player:
    IconOutlineColor: 33, 136, 253
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Chartreuse
    LabelFontSize: 14
    LabelFont: Formal 436
  PartyPlayer:
    IconOutlineColor: Chartreuse
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Chartreuse
    LabelFontSize: 14
    LabelFont: Formal 436
  NonPartyPlayer:
    IconOutlineColor: Orange
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Orange
    LabelFontSize: 14
    LabelFont: Formal 436
  HostilePlayer:
    IconOutlineColor: Red
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LineColor: Red
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Red
    LabelFontSize: 14
    LabelFont: Formal 436
  Corpse:
    IconOutlineColor: Magenta
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LineColor: Magenta
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Magenta
    LabelFontSize: 14
    LabelFont: Formal 436
  Portal:
    IconOutlineColor: Yellow
    IconShape: Portal
    IconSize: 3
    IconThickness: 2
    LabelColor: Yellow
    LabelFontSize: 14
    LabelFont: Formal 436
  SuperChest:
    IconColor: 17, 255, 0
    IconShape: Square
    IconSize: 4
  NormalChest:
    IconColor: 17, 128, 0
    IconShape: Square
    IconSize: 3
  LockedChest:
    IconColor: Maroon
    IconShape: Square
    IconSize: 3
  TrappedChest:
    IconColor: Red
    IconShape: Square
    IconSize: 4
  Shrine:
    IconColor: 255, 218, 100
    IconShape: Polygon
    IconSize: 5
    LabelColor: 255, 218, 100
    LabelFontSize: 14
    LabelFont: Formal 436
  ArmorWeapRack:
    IconColor: 132, 132, 132
    IconShape: Square
    IconSize: 4
  Item:
    IconColor: DarkOrange
    IconShape: Ellipse
    IconSize: 4
    LabelFontSize: 16
    LabelFont: Exocet Blizzard Mixed Caps
ItemLog:
  Enabled: true
  FilterFileName: ItemFilter.yaml
  PlaySoundOnDrop: true
  SoundFile: ''
  SoundVolume: 100
  DisplayForSeconds: 45
  LabelFont: Exocet Blizzard Mixed Caps
  LabelFontSize: 14
MapColorConfiguration:
  Border: 255, 255, 255
GameInfo:
  ShowGameIP: true
  HuntingIP: 0.0.0.0
  ShowAreaLevel: true
  ShowOverlayFPS: false
  LabelFont: Exocet Blizzard Mixed Caps
  LabelFontSize: 14
D2Path: ''
LanguageCode: enUS
